version: '2'

services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: php
    volumes:
      - ./html:/html
