version: '2'

services:

  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./html:/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7-fpm
    volumes:
      - ./html:/html
